
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package genericxml;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int boton_ = 22;
  public static final int defecto_ = 20;
  public static final int multimedia_ = 21;
  public static final int alto_ = 31;
  public static final int false_ = 7;
  public static final int tipo_ = 25;
  public static final int cursiva_ = 38;
  public static final int igual = 11;
  public static final int id_ = 24;
  public static final int referencia_ = 42;
  public static final int textoPlano = 3;
  public static final int mayorque = 9;
  public static final int ancho_ = 32;
  public static final int accionfinal_ = 28;
  public static final int enviar_ = 23;
  public static final int borde_ = 33;
  public static final int autoreproduccion_ = 44;
  public static final int accioninicial_ = 27;
  public static final int EOF = 0;
  public static final int y_ = 30;
  public static final int error = 1;
  public static final int true_ = 6;
  public static final int tstring = 2;
  public static final int entero = 4;
  public static final int listadatos_ = 18;
  public static final int accion_ = 41;
  public static final int contenedor_ = 15;
  public static final int minimo_ = 40;
  public static final int menorque = 10;
  public static final int control_ = 17;
  public static final int maximo_ = 39;
  public static final int fuente_ = 35;
  public static final int nombre_ = 34;
  public static final int path_ = 43;
  public static final int dato_ = 19;
  public static final int importar_ = 13;
  public static final int tam_ = 36;
  public static final int texto_ = 16;
  public static final int codigo = 8;
  public static final int negrita_ = 37;
  public static final int x_ = 29;
  public static final int ventana_ = 14;
  public static final int decimal = 5;
  public static final int diagonal = 12;
  public static final int color_ = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tstring",
  "textoPlano",
  "entero",
  "decimal",
  "true_",
  "false_",
  "codigo",
  "mayorque",
  "menorque",
  "igual",
  "diagonal",
  "importar_",
  "ventana_",
  "contenedor_",
  "texto_",
  "control_",
  "listadatos_",
  "dato_",
  "defecto_",
  "multimedia_",
  "boton_",
  "enviar_",
  "id_",
  "tipo_",
  "color_",
  "accioninicial_",
  "accionfinal_",
  "x_",
  "y_",
  "alto_",
  "ancho_",
  "borde_",
  "nombre_",
  "fuente_",
  "tam_",
  "negrita_",
  "cursiva_",
  "maximo_",
  "minimo_",
  "accion_",
  "referencia_",
  "path_",
  "autoreproduccion_"
  };
}

