
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package gdato;

/** CUP generated class containing symbol constants. */
public class SymGDato {
  /* terminals */
  public static final int diagonal = 8;
  public static final int mayorque = 6;
  public static final int decimal = 4;
  public static final int EOF = 0;
  public static final int tstring = 2;
  public static final int entero = 3;
  public static final int error = 1;
  public static final int identificador = 5;
  public static final int menorque = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tstring",
  "entero",
  "decimal",
  "identificador",
  "mayorque",
  "menorque",
  "diagonal"
  };
}

