
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package fs;

/** CUP generated class containing symbol constants. */
public class SymFs {
  /* terminals */
  public static final int var_ = 44;
  public static final int imprimir_ = 45;
  public static final int igualigual = 34;
  public static final int defecto_ = 53;
  public static final int porigual = 42;
  public static final int menosigual = 41;
  public static final int caso_ = 52;
  public static final int nulo_ = 7;
  public static final int coma = 17;
  public static final int igual = 39;
  public static final int identificador = 6;
  public static final int funcion_ = 54;
  public static final int mayorque = 30;
  public static final int masigual = 40;
  public static final int menosmenos = 29;
  public static final int puntoycoma = 16;
  public static final int si_ = 49;
  public static final int llaveIzquierda = 10;
  public static final int masmas = 28;
  public static final int verdadero_ = 8;
  public static final int menos = 22;
  public static final int EOF = 0;
  public static final int diagonaligual = 43;
  public static final int mas = 21;
  public static final int error = 1;
  public static final int umas = 27;
  public static final int tstring = 2;
  public static final int detener_ = 47;
  public static final int retornar_ = 48;
  public static final int or = 37;
  public static final int entero = 4;
  public static final int parIzquierda = 12;
  public static final int menorigual = 33;
  public static final int punto = 18;
  public static final int corcheteDerecha = 15;
  public static final int dospuntos = 19;
  public static final int menorque = 31;
  public static final int parDerecha = 13;
  public static final int sino_ = 50;
  public static final int potencia = 25;
  public static final int mayorigual = 32;
  public static final int corcheteIzquierda = 14;
  public static final int importar_ = 46;
  public static final int diferente = 35;
  public static final int llaveDerecha = 11;
  public static final int not = 38;
  public static final int and = 36;
  public static final int umenos = 26;
  public static final int asterisco = 23;
  public static final int selecciona_ = 51;
  public static final int falso_ = 9;
  public static final int interrogacion = 20;
  public static final int decimal = 5;
  public static final int diagonal = 24;
  public static final int tchar = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tstring",
  "tchar",
  "entero",
  "decimal",
  "identificador",
  "nulo_",
  "verdadero_",
  "falso_",
  "llaveIzquierda",
  "llaveDerecha",
  "parIzquierda",
  "parDerecha",
  "corcheteIzquierda",
  "corcheteDerecha",
  "puntoycoma",
  "coma",
  "punto",
  "dospuntos",
  "interrogacion",
  "mas",
  "menos",
  "asterisco",
  "diagonal",
  "potencia",
  "umenos",
  "umas",
  "masmas",
  "menosmenos",
  "mayorque",
  "menorque",
  "mayorigual",
  "menorigual",
  "igualigual",
  "diferente",
  "and",
  "or",
  "not",
  "igual",
  "masigual",
  "menosigual",
  "porigual",
  "diagonaligual",
  "var_",
  "imprimir_",
  "importar_",
  "detener_",
  "retornar_",
  "si_",
  "sino_",
  "selecciona_",
  "caso_",
  "defecto_",
  "funcion_"
  };
}

